### ISSUE TITLE
append_path vs. full_path

### ISSUE THREAD

**Issue by firstprinciples** [rediscovery-io/remo-python#84]
In line 276 of: https://github.com/rediscovery-io/remo-python/blob/master/remo/domain/dataset.py
this should be `full_path` not `append_path`.

**Comment by drewlr** [comment]
Thanks for this @firstprinciples !

This is fixed now. What we changed:

- `export_annotations` is now a hidden function. The docstring wasn't clear, so not sure if it was intentional on your side to use it as that function exports to Binary format. You can call  `_export_annotations()` if that was what you wanted, or otherwise you can use `export_annotations_to_file` to save to file

- we standardized the parameter to be append_path

- better docstrings 

If no objection on your side, I will close the issue.

**Comment by firstprinciples** [comment]
Okay thank you. I will use export_annotations_to_file() from now on. Is there a way to make that export not as a zip file? Just a standard csv would be preferred, but not a big deal.

**Comment by drewlr** [comment]
No prob! If you don't care about image tags, you could do

```
export_annotations_to_file(output_file = 'annotations.csv', annotation_format = 'csv', export_tags = False)
```

and it would export the annotations in csv.

We are currently exporting tags in a separate file, so if you want them too the output will be a zip unfortunately.

**Comment by firstprinciples** [comment]
That makes sense! Thanks for the help.
